### ISSUE TITLE
use appropriate `time_type` and format of time values in preview/plot/export data

### ISSUE THREAD

**Issue by melange396** [cmu-delphi/signal_documentation#170]
The "Preview data", "Plot data", and "Export data" functionality on the individual signal pages work well for data with a `time_type` of "`day`", but not for signals that have a "`week`" type...

* for "preview data" and "export data" modes, [`startDate` and `endDate`](https://github.com/cmu-delphi/signal_documentation/blob/9f11821e0834addded22276f8ef7b58f34c8d926/src/templates/signals/data_visualization_export.html#L255-L256) should be converted to a corresponding EpiWeek value (with format `YYYYWW`, like "200051" for the 51st week of the year 2000)
  * `delphi_utils` [uses](https://github.com/cmu-delphi/covidcast-indicators/blob/b3fe2cb3db8137763ddb99dd4bc13eb6f9983fca/_delphi_utils_python/delphi_utils/export.py#L103) the [`epiweeks` package](https://github.com/dralshehri/epiweeks) for this

* for "plot data" mode, this should use "day" or "week" as appropriate for the signal:
https://github.com/cmu-delphi/signal_documentation/blob/9f11821e0834addded22276f8ef7b58f34c8d926/src/templates/signals/data_visualization_export.html#L250 as the "preview data" mode already does: https://github.com/cmu-delphi/signal_documentation/blob/9f11821e0834addded22276f8ef7b58f34c8d926/src/templates/signals/data_visualization_export.html#L269 (note: time_type of "week" is not yet fully supported in epivis)

**Comment by dmytrotsko** [comment]
Solved this issue in the latest PR.
