### ISSUE TITLE
Allow filtering on "active" signals 

### ISSUE THREAD

**Issue by melange396** [cmu-delphi/signal_documentation#30]
There is an active column in the old signals spreadsheet, and it looks like its incorporated in the model [here](https://github.com/cmu-delphi/signal_documentation/blob/f3507d610df02a18b3a80b73f133eb0144c97ba4/src/signals/resources.py#L66).

For instance, https://staging/signals/signals/905/ (`safegraph-daily` / "Part Time Work/School") lists in its description that it was "Discontinued April 19th, 2021".  All of our `fb-survey` signals are currently inactive.  Such information is very likely to be valuable to a researcher browsing for signals.

We may possibly want to display this as a column in the main list-of-signals view, and definitely want to show it on an individual signal's detail page.

**Comment by BrainIsDead** [comment]
Done
