### ISSUE TITLE
Make both lefthand and righthand menus collapsible and collapsed by default

### ISSUE THREAD

**Issue by carlynvandyke** [cmu-delphi/signal_documentation#36]
I don't think either menu needs to be visible for people landing on the page. The lefthand menu can continue to use the hamburger button (moved as specified by George [here](https://github.com/cmu-delphi/signal_documentation/issues/25)) and the righthand search menu can have a different button to open it. This will also help with our issue of the signals table being too wide to fit on the page.

@BrainIsDead at one point you shared a site that had different options for Django styling, menus, etc.- could you share again?

**Comment by BrainIsDead** [comment]
https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/

**Comment by BrainIsDead** [comment]
Done https://github.com/cmu-delphi/signal_documentation/pull/32
