### ISSUE TITLE
Remove extra columns from signals table

### ISSUE THREAD

**Issue by carlynvandyke** [cmu-delphi/signal_documentation#37]
Let's remove: 

- available geography
- signal type
- format
- temporal resolution
- link

from the home page signals table. (Yes, I know I'm the one who said to have them there 😁, but now that I see it it's too much!)

Once we remove those columns we can reassess what we need to do about column width.

**Comment by BrainIsDead** [comment]
Done https://github.com/cmu-delphi/signal_documentation/pull/32
